### ISSUE TITLE
Move isc.org website to this GH org

### ISSUE THREAD

**Issue by cewilliams** [InnerSourceCommons/infrastructure#1]

**Comment by cewilliams** [comment]
- [x] Clone current repo
- [x] Create new CI with new org-based api key
- [x] Update repo contents to remove `/InnerSourceCommons/` path from any url or url fragment 
- [x] Update domain registration to remove redirect, add A and CNAME records pointing to GH servers
- [x] Update current repo to serve redirect page

**Comment by NewMexicoKid** [comment]
> * [ ]  Update repo contents to remove `/InnerSourceCommons/` path from any url or url fragment

Do you have a script for this already?
Do we need to have something to do this action not just in the website but also the wiki?
