### ISSUE TITLE
Slack-Inviter paid-teams-only problem

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/infrastructure#8]
As visible in https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/97 and https://github.com/InnerSourceCommons/innersourcecommons.org/issues/54 our current slack inviter refuses to work due to being on the free plan now.

Both issues describe the same problem that I would deem a problem with our infrastructure.
A short research would offer this approach: 
- https://get.slack.help/hc/en-us/articles/201330256-Invite-new-members-to-your-workspace#share-an-invite-link
  - this apparently requires to regularly rotate the invite link 
- https://intoli.com/blog/make-a-public-slack-community/
  - looks interesting and indeed does work, possibly also with a free plan Slack.
- We're currently using [SlackIn](https://github.com/rauchg/slackin), does someone have experience if the free plan limits would represent an issue with [this](https://github.com/outsideris/slack-invite-automation) inviter too (i.e. a general Slack free plan limit)?

**Comment by lenucksi** [comment]
We had the inviter configured with the "join specific channels on new account" option. 
This feature appears to only work with paid Slacks as I got to know while deploying an alternative to Heroku. 

> SLACK_CHANNELS
> Comma-separated list of single guest channels to invite them to (leave blank for a normal, all-channel invite). In order to make this work, you have to have a paid account. You'll only be able to invite as many people as your number of paying members times 5.
> 

The alternative for now lives here: https://innersourcecommons-inviter.herokuapp.com/ 

Do we want to keep that URL and deployment or fix (upgrade) the other one?
I can provide a website change PR for the new one but would be happy if someone else would make one too.

**Comment by StingRayZA** [comment]
I don't see any drawbacks in just setting up the new one as the 'main' one...
I've created a PR for the website to do the changeover. (https://github.com/InnerSourceCommons/innersourcecommons.org/pull/56)
would it be worthwhile creating a (private?) repo to store the config/code of the inviter?

**Comment by lenucksi** [comment]
Thanks for making the PR. 
What has been deployed is [whatever has been the current master in rauchg/slackin as of Monday](https://github.com/rauchg/slackin/commit/f52054363ea885bdeeb6b2c03f9a602251a41731). [...] They don't do releases anymore since some years.

The only changes we made are custom credentials. Those I can definitely store in the vault @cewilliams has provided me with or we make a repo using [GoPass](https://github.com/gopasspw/gopass). GoPass has been successfully vetted as being good&useful by colleagues of mine.

**Comment by rrrutledge** [comment]
Since the `innersourcecommons-inviter` link on the main page is working again I deleted the magic join link from _Slack_ that I had created at one point.

**Comment by rrrutledge** [comment]
https://github.com/InnerSourceCommons/innersourcecommons.org/pull/57 should finish off fixing this.

**Comment by lenucksi** [comment]
I would say that this is done for now. Thanks for making the PR's with the URL-updates and the reviews & tests.
